version: '3'

services:
  db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    user: "${UID}:${GID}"
    volumes:
      - ./docker/volumes:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    restart: always

  # app:
  #   image: node:18-alpine
  #   restart: always
  #   command: sh -c "yarn && yarn db:generate && yarn start:dev"
  #   working_dir: /app
  #   environment:
  #     DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@${DOCKER_DB_HOST}:${DOCKER_DB_PORT}/${DB_NAME}
  #   env_file:
  #     - .env
  #   ports:
  #     - ${BACKEND_PORT}:${BACKEND_PORT}
  #   depends_on:
  #     - db
  #   volumes:
  #     - ./:/app
